### ISSUE TITLE
"# Vluchten in gebied" not correct.

### ISSUE THREAD

**Issue by BjornSchalks1976** [emi662002/homey.flightradar-issues#2]
"# Vluchten in gebied" doesn't counts correct.
![Screenshot_20240409_164936_Homey](https://github.com/emi662002/homey.flightradar-issues/assets/154658728/ecd45dfe-fe45-4e25-909b-be2e8d83d1a1)

**Comment by emi662002** [comment]
I think you mean the decimal numbers. I don't know how that come, I always
work with integer numbers. Homey seems to do something with count vs time

Op di 9 apr. 2024 18:12 schreef BjornSchalks1976 ***@***.***>:

**Comment by emi662002** [comment]
Fixed timezone.

**Comment by BjornSchalks1976** [comment]
Can je tell me the status for this issue?
At this time there are always 5 planes in my area.
And its still counting trough

**Comment by emi662002** [comment]
> Can je tell me the status for this issue? At this time there are always 5 planes in my area. And its still counting trough

Oh ok I didn't understand the issue and thought it was the decimal numbers. I will check it soon

**Comment by BjornSchalks1976** [comment]
it takes a very long time before you actually look at it and solve it.

**Comment by emi662002** [comment]
> it takes a very long time before you actually look at it and solve it.

Yeah, you know community apps are mostly developed on people's own hobby time, so it has its own pace. Holidays for example. I think it's fixed now. Let me know. And don't forget to leave a contribution it motivates to find the time :D  https://community.homey.app/t/app-pro-flightradar24/107268

**Comment by BjornSchalks1976** [comment]
It looks like it works now
