### ISSUE TITLE
App is useing wrong timezone

### ISSUE THREAD

**Issue by BjornSchalks1976** [emi662002/homey.flightradar-issues#3]
The App is useing the wrong timezone
![Screenshot_20240412_081750_WhatsApp](https://github.com/emi662002/homey.flightradar-issues/assets/154658728/846b848b-15dd-48a9-ae0b-da9d957034fa)
![Screenshot_20240412_081932_WhatsApp](https://github.com/emi662002/homey.flightradar-issues/assets/154658728/4c331284-b519-40b1-9218-f52e5d80ae80)
timezone

**Comment by emi662002** [comment]
Fixed timezone
